/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class meng_hotup_utils_BsPatchUtil */

#ifndef _Included_meng_hotup_utils_BsPatchUtil
#define _Included_meng_hotup_utils_BsPatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     meng_hotup_utils_BsPatchUtil
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_meng_hotup_utils_BsPatchUtil_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
